#!/bin/sh

# Copyright (C) 2024 Nike Okoronkwo
# All Rights Reserved
# This code is governed by an [_] that can be found in the LICENSE file

SRCDIR=$(dirname $0)
RUBY="ruby"

if command -v ruby &> /dev/null; then
   RUBY="ruby"
else
    echo "In order to build this project, you will need ruby installed."
    exit 1
fi

exec "$RUBY" "$SRCDIR/build.rb" $@