/// Generated by package `env` in `pritt`.
/// For more information, visit: []


part of 'example.dart';

// **************************************************************************
// Generator: EnvEmbedder
// **************************************************************************

String MY_SECRET = "hello";

String OUR_SECRET = '';
